title: Justin Cassner
logo: headshot.jpg
description: Technical Skills Portfolio
show_downloads: true
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
